export const getBooksUrl = "http://henri-potier.xebia.fr/books"
export const getOfferUrl =
  "http://henri-potier.xebia.fr/books/$products/commercialOffers"
export const REMOVE_FROM_CART = "REMOVEFROMCART"
export const HIDE_SLIDER = "HIDE_SLIDER"
export const SHOW_SLIDER = "SHOW_SLIDER"
export const ITEM_ALREADY_ADDED = "ITEM_ALREADY_ADDED"
export const ADD_TO_CART = "ADD_TO_CART"
export const LOADING_DATA = "LOADING_DATA"
export const LOADED_DATA = "LOADED_DATA"
export const ERROR = "ERROR"
export const SEARCHING = "SEARCHING"
export const CANCEL_SEARCH = "CANCEL_SEARCH"
