export const mobileBreakpoint = 649;
export const staletimeForSearchQuery = 60 * 1000 * 10; // 10minutes
export const APIJsonPlaceholder = 'https://jsonplaceholder.typicode.com/posts';
export const footerMenu = "/es/get-menu/footer";
export const mainMenu = "/es/get-menu/main";
export const espaceSouvenirs = '/es/get-entity/espace_souvenirs';
export const lineBreak = "<br />";
export const postApiUrl = "/es/entity-save-field";
export const postUserUrl = "/es/get-user";
export const postUserUpdateUrl = "/es/user-update";
export const homageMachineName = "field_es_homage";
export const bioMachineName = "field_es_bio";
export const accueil = "accueil";
export const messages = "messages";
export const biographie = "biographie";
export const messagesPerPage = 8;